### PR TITLE
Report test coverage using nyc

### PR DESCRIPTION
**Pull request by dhui**
https://istanbul.js.org/docs/tutorials/mocha/

### CODE REVIEW

**Comment by dhui** [comment]
Looks like the build for node 4 is failing. Do we need to continue supporting node 4?

**Comment by jhermsmeier** [comment]
Fist of all, thank you for the work you've put in!
With the fairly minimal size of this module I have a hard time seeing the benefits of reporting test coverage though. Further, this breaks the Node v4 build due to `nyc`'s incompatibility.
While there's no real reason to keep supporting Node v4, it'd have to be a major version bump to discontinue support for it, and there's also no reason to drop Node v4 support either.
So I'll close this for now, possibly to be revisited at a later time.
If you have some strong arguments in its favour, I'd love to hear them though.

**Comment by dhui** [comment]
Test coverage stats may have been useful in catching the broken `has()` implementation.

**Comment by dhui** [comment]
I've downgraded to a version of `nyc` that supports node v4: https://travis-ci.org/dhui/node-http-link-header/builds/464138253

**Pull request closed without merging**
