### PR TITLE
link: fix parsing links with `nopush`

### PR DESCRIPTION
**Pull request by adamraine**
Fixes https://github.com/jhermsmeier/node-http-link-header/issues/29

### CODE REVIEW

**Comment by paulirish** [comment]
@jhermsmeier are you able to merge and rls this soon? Up in the [Lighthouse](https://github.com/GoogleChrome/lighthouse) project this is an urgent bug for us and we may fork if we need to.

**Comment by jhermsmeier** [comment]
Hey hey! Yeah, let me do that now, and will have a deeper look at things in the coming days.

**Comment by jhermsmeier** [comment]
Published in `http-link-header@1.1.1`

**Comment by paulirish** [comment]
Well that was prompt!! lol. Really appreciate it.  Thank you sir!

**Pull request merged**
